DUPLICATES = {
    "applicant_ethnicity-2",
    "applicant_ethnicity-3",
    "applicant_ethnicity-4",
    "applicant_ethnicity-5",
    "co-applicant_ethnicity-2",
    "co-applicant_ethnicity-3",
    "co-applicant_ethnicity-4",
    "co-applicant_ethnicity-5",
    "applicant_race-2",
    "applicant_race-3",
    "applicant_race-4",
    "applicant_race-5",
    "co-applicant_race-2",
    "co-applicant_race-3",
    "co-applicant_race-4",
    "co-applicant_race-5",
    "aus-2",
    "aus-3",
    "aus-4",
    "aus-5",
    "denial_reason-2",
    "denial_reason-3",
    "denial_reason-4",
}

UNNEEDED = {}
