MAPPER = {
    # "activity_year": {},
    # "lei": {},
    # "derived_msa-md": {},
    # "state_code": {},
    # "county_code": {},
    # "census_tract": {},
    # "conforming_loan_limit": {},
    # "derived_loan_product_type": {},
    # "derived_dwelling_category": {},
    # "derived_ethnicity": {},
    # "derived_race": {},
    # "derived_sex": {},
    "action_taken": {
        "1": "Loan originated",
        "2": "Application approved but not accepted",
        "3": "Application denied",
        "4": "Application withdrawn by applicant",
        "5": "File closed for incompleteness",
        "6": "Purchased loan",
        "7": "Preapproval request denied",
        "8": "Preapproval request approved but not accepted",
    },
    "purchaser_type": {
        "0": "Not applicable",
        "1": "Fannie Mae",
        "2": "Ginnie Mae",
        "3": "Freddie Mac",
        "4": "Farmer Mac",
        "5": "Private securitizer",
        "6": "Commercial bank, savings bank, or savings association",
        "71": "Credit union, mortgage company, or finance company",
        "72": "Life insurance company",
        "8": "Affiliate institution",
        "9": "Other type of purchaser",
    },
    "preapproval": {
        "1": "Preapproval requested",
        "2": "Preapproval not requested",
    },
    "loan_type": {
        "1": "Conventional (not insured or guaranteed by FHA, VA, RHS, or FSA)",
        "2": "Federal Housing Administration insured (FHA)",
        "3": "Veterans Affairs guaranteed (VA)",
        "4": "USDA Rural Housing Service or Farm Service Agency guaranteed (RHS or FSA)",
    },
    "loan_purpose": {
        "1": "Home purchase",
        "2": "Home improvement",
        "31": "Refinancing",
        "32": "Cash-out refinancing",
        "4": "Other purpose",
        "5": "Not applicable",
    },
    "lien_status": {
        "1": "Secured by a first lien",
        "2": "Secured by a subordinate lien",
    },
    "reverse_mortgage": {
        "1": "Reverse mortgage",
        "2": "Not a reverse mortgage",
        "1111": "Exempt",
    },
    "open-end_line_of_credit": {
        "1": "Open-end line of credit",
        "2": "Not an open-end line of credit",
        "1111": "Exempt",
    },
    "business_or_commercial_purpose": {
        "1": "Primarily for a business or commercial purpose",
        "2": "Not primarily for a business or commercial purpose",
        "1111": "Exempt",
    },
    # "loan_amount": {},
    # "loan_to_value_ratio": {},
    # "interest_rate": {},
    # "rate_spread": {},
    "hoepa_status": {
        "1": "High-cost mortgage",
        "2": "Not a high-cost mortgage",
        "3": "Not applicable",
    },
    # "total_loan_costs": {},
    # "total_points_and_fees": {},
    # "origination_charges": {},
    # "discount_points": {},
    # "lender_credits": {},
    # "loan_term": {},
    # "prepayment_penalty_term": {},
    # "intro_rate_period": {},
    "negative_amortization": {
        "1": "Negative amortization",
        "2": "No negative amortization",
        "1111": "Exempt",
    },
    "interest_only_payment": {
        "1": "Interest-only payments",
        "2": "No interest-only payments",
        "1111": "Exempt",
    },
    "balloon_payment": {
        "1": "Balloon payment",
        "2": "No balloon payment",
        "1111": "Exempt",
    },
    "other_nonamortizing_features": {
        "1": "Other non-fully amortizing features",
        "2": "No other non-fully amortizing features",
        "1111": "Exempt",
    },
    # "property_value": {},
    "construction_method": {
        "1": "Site-built",
        "2": "Manufactured home",
    },
    "occupancy_type": {
        "1": "Principal residence",
        "2": "Second residence",
        "3": "Investment property",
    },
    "manufactured_home_secured_property_type": {
        "1": "Manufactured home and land",
        "2": "Manufactured home and not land",
        "3": "Not applicable",
        "1111": "Exempt",
    },
    "manufactured_home_land_property_interest": {
        "1": "Direct ownership",
        "2": "Indirect ownership",
        "3": "Paid leasehold",
        "4": "Unpaid leasehold",
        "5": "Not applicable",
        "1111": "Exempt",
    },
    # "total_units": {},
    # "multifamily_affordable_units": {},
    # "income": {},
    # "debt_to_income_ratio": {},
    "applicant_credit_score_type": {
        "1": "Equifax Beacon 5.0",
        "2": "Experian Fair Isaac",
        "3": "FICO Risk Score Classic 04",
        "4": "FICO Risk Score Classic 98",
        "5": "VantageScore 2.0",
        "6": "VantageScore 3.0",
        "7": "More than one credit scoring model",
        "8": "Other credit scoring model",
        "9": "Not applicable",
        "1111": "Exempt",
    },
    "co-applicant_credit_score_type": {
        "1": "Equifax Beacon 5.0",
        "2": "Experian Fair Isaac",
        "3": "FICO Risk Score Classic 04",
        "4": "FICO Risk Score Classic 98",
        "5": "VantageScore 2.0",
        "6": "VantageScore 3.0",
        "7": "More than one credit scoring model",
        "8": "Other credit scoring model",
        "9": "Not applicable",
        "10": "No co-applicant",
        "1111": "Exempt",
    },
    "applicant_ethnicity-1": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
        "3": "Information not provided by applicant in mail, internet, or telephone application",
        "4": "Not applicable",
    },
    "applicant_ethnicity-2": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "applicant_ethnicity-3": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "applicant_ethnicity-4": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "applicant_ethnicity-5": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "co-applicant_ethnicity-1": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
        "3": "Information not provided by applicant in mail, internet, or telephone application",
        "4": "Not applicable",
        "5": "No co-applicant",
    },
    "co-applicant_ethnicity-2": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "co-applicant_ethnicity-3": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "co-applicant_ethnicity-4": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "co-applicant_ethnicity-5": {
        "1": "Hispanic or Latino",
        "11": "Mexican",
        "12": "Puerto Rican",
        "13": "Cuban",
        "14": "Other Hispanic or Latino",
        "2": "Not Hispanic or Latino",
    },
    "applicant_ethnicity_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
    },
    "co-applicant_ethnicity_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
        "4": "No co-applicant",
    },
    "applicant_race-1": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
        "6": "Information not provided by applicant in mail, internet, or telephone application",
        "7": "Not applicable",
    },
    "applicant_race-2": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "applicant_race-3": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "applicant_race-4": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "applicant_race-5": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "co-applicant_race-1": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
        "6": "Information not provided by applicant in mail, internet, or telephone application",
        "7": "Not applicable",
        "8": "No co-applicant",
    },
    "co-applicant_race-2": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "co-applicant_race-3": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "co-applicant_race-4": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "co-applicant_race-5": {
        "1": "American Indian or Alaska Native",
        "2": "Asian",
        "21": "Asian Indian",
        "22": "Chinese",
        "23": "Filipino",
        "24": "Japanese",
        "25": "Korean",
        "26": "Vietnamese",
        "27": "Other Asian",
        "3": "Black or African American",
        "4": "Native Hawaiian or Other Pacific Islander",
        "41": "Native Hawaiian",
        "42": "Guamanian or Chamorro",
        "43": "Samoan",
        "44": "Other Pacific Islander",
        "5": "White",
    },
    "applicant_race_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
    },
    "co-applicant_race_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
        "4": "No co-applicant",
    },
    "applicant_sex": {
        "1": "Male",
        "2": "Female",
        "3": "Information not provided by applicant in mail, internet, or telephone application",
        "4": "Not applicable",
        "6": "Applicant selected both male and female",
    },
    "co-applicant_sex": {
        "1": "Male",
        "2": "Female",
        "3": "Information not provided by applicant in mail, internet, or telephone application",
        "4": "Not applicable",
        "5": "No co-applicant",
        "6": "Co-applicant selected both male and female",
    },
    "applicant_sex_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
    },
    "co-applicant_sex_observed": {
        "1": "Collected on the basis of visual observation or surname",
        "2": "Not collected on the basis of visual observation or surname",
        "3": "Not applicable",
        "4": "No co-applicant",
    },
    # "applicant_age": {},
    # "co-applicant_age": {},
    # "applicant_age_above_62": {},
    # "co-applicant_age_above_62": {},
    "submission_of_application": {
        "1": "Submitted directly to your institution",
        "2": "Not submitted directly to your institution",
        "3": "Not applicable",
        "1111": "Exempt",
    },
    "initially_payable_to_institution": {
        "1": "Initially payable to your institution",
        "2": "Not initially payable to your institution",
        "3": "Not applicable",
        "1111": "Exempt",
    },
    "aus-1": {
        "1": "Desktop Underwriter (DU)",
        "2": "Loan Prospector (LP) or Loan Product Advisor",
        "3": "Technology Open to Approved Lenders (TOTAL) Scorecard",
        "4": "Guaranteed Underwriting System (GUS)",
        "5": "Other",
        "6": "Not applicable",
        "7": "Internal Proprietary System",
        "1111": "Exempt",
    },
    "aus-2": {
        "1": "Desktop Underwriter (DU)",
        "2": "Loan Prospector (LP) or Loan Product Advisor",
        "3": "Technology Open to Approved Lenders (TOTAL) Scorecard",
        "4": "Guaranteed Underwriting System (GUS)",
        "5": "Other",
        "7": "Internal Proprietary System",
    },
    "aus-3": {
        "1": "Desktop Underwriter (DU)",
        "2": "Loan Prospector (LP) or Loan Product Advisor",
        "3": "Technology Open to Approved Lenders (TOTAL) Scorecard",
        "4": "Guaranteed Underwriting System (GUS)",
        "7": "Internal Proprietary System",
    },
    "aus-4": {
        "1": "Desktop Underwriter (DU)",
        "2": "Loan Prospector (LP) or Loan Product Advisor",
        "3": "Technology Open to Approved Lenders (TOTAL) Scorecard",
        "4": "Guaranteed Underwriting System (GUS)",
        "7": "Internal Proprietary System",
    },
    "aus-5": {
        "1": "Desktop Underwriter (DU)",
        "2": "Loan Prospector (LP) or Loan Product Advisor",
        "3": "Technology Open to Approved Lenders (TOTAL) Scorecard",
        "4": "Guaranteed Underwriting System (GUS)",
        "7": "Internal Proprietary System",
    },
    "denial_reason-1": {
        "1": "Debt-to-income ratio",
        "2": "Employment history",
        "3": "Credit history",
        "4": "Collateral",
        "5": "Insufficient cash (downpayment, closing costs)",
        "6": "Unverifiable information",
        "7": "Credit application incomplete",
        "8": "Mortgage insurance denied",
        "9": "Other",
        "10": "Not applicable",
    },
    "denial_reason-2": {
        "1": "Debt-to-income ratio",
        "2": "Employment history",
        "3": "Credit history",
        "4": "Collateral",
        "5": "Insufficient cash (downpayment, closing costs)",
        "6": "Unverifiable information",
        "7": "Credit application incomplete",
        "8": "Mortgage insurance denied",
        "9": "Other",
    },
    "denial_reason-3": {
        "1": "Debt-to-income ratio",
        "2": "Employment history",
        "3": "Credit history",
        "4": "Collateral",
        "5": "Insufficient cash (downpayment, closing costs)",
        "6": "Unverifiable information",
        "7": "Credit application incomplete",
        "8": "Mortgage insurance denied",
        "9": "Other",
    },
    "denial_reason-4": {
        "1": "Debt-to-income ratio",
        "2": "Employment history",
        "3": "Credit history",
        "4": "Collateral",
        "5": "Insufficient cash (downpayment, closing costs)",
        "6": "Unverifiable information",
        "7": "Credit application incomplete",
        "8": "Mortgage insurance denied",
        "9": "Other",
    },
    # "tract_population": {},
    # "tract_minority_population_percent": {},
    # "ffiec_msa_md_median_family_income": {},
    # "tract_to_msa_income_percentage": {},
    # "tract_owner_occupied_units": {},
    # "tract_one_to_four_family_homes": {},
    # "tract_median_age_of_housing_units": {},
}
