# Generated by Django 5.0.3 on 2024-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financial_information",
            name="loan_term",
        ),
        migrations.AddField(
            model_name="financial_information",
            name="monthly_loan_term",
            field=models.IntegerField(default=0),
        ),
    ]
