# Generated by Django 5.0.3 on 2024-04-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_financial_information_loan_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financial_information",
            name="interest_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
