# Generated by Django 5.0.3 on 2024-04-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_financial_information_debt_ratio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financial_information",
            name="interest_rate",
        ),
        migrations.AlterField(
            model_name="financial_information",
            name="debt_ratio",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="financial_information",
            name="down_payment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="financial_information",
            name="loan_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="financial_information",
            name="property_value",
            field=models.FloatField(default=0.0),
        ),
    ]
