# Generated by Django 5.0.3 on 2024-04-30 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_financial_information_interest_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financial_information",
            name="debt_ratio",
        ),
    ]
